### ISSUE TITLE
没有做边界处理和，旋转处理

### ISSUE THREAD

**Issue by rendaoer** [NightsWatchGames/tetris#1]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/46780118/226773449-a1847b2b-38f9-4426-af7e-c7f12ad12bbf.png">
边界不会阻挡，一格空间也可以旋转
[doge]

**Comment by lewiszlw** [comment]
你有时间感兴趣的话可以提个pr修复～
没有的话我抽时间修复下

**Comment by lewiszlw** [comment]
应该是修复了但没部署最新wasm到站点 https://github.com/NightsWatchGames/tetris/commit/70bfbd622cbc04295127545661d1c5b8bd4926c2 , 能本地cargo run看看还有问题吗？
Edit. 我刚推了最新wasm到站点，你再试试，应该是没这个问题了

**Comment by rendaoer** [comment]
可以的，没问题，我有时间学习下
