### ISSUE TITLE
no instant render when the last line disappears

### ISSUE THREAD

**Issue by chanmaoganda** [NightsWatchGames/tetris#7]
在消除一行以后渲染没有及时更新啊
只有新方块落到他上边也不会渲染????

**Comment by lewiszlw** [comment]
看起来是触发了bug，能否稳定复现呢？

**Comment by chanmaoganda** [comment]
# 可以稳定复现
## 每次第一次进入的关卡是完全相同的

https://github.com/NightsWatchGames/tetris/assets/121547473/4fca2b32-42f5-4289-93b8-03255da0a63f

**Comment by lewiszlw** [comment]
网页版没更新，刚更新试了下没问题了
